env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-unused-vars:
    - off
globals: 
  componentHandler : true #MaterialDesignLite Global